[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc = { version = "0.1.0", path = "../aoc" }
puzlib = { git = "https://github.com/MrRobotMan/puzlib", version = "0.1.0" }

[[bin]]
name = "aoc202501"

[[bin]]
name = "aoc202502"
