[package]
name = "aoc2024"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = {path = "../aoc"}
itertools = "0.13.0"
pathfinding = "4.12.0"
regex = "1.11.1"
